language: python
python:
        -2.7
        -3.5
        -3.6
before_install:
        -python --version
os:
        - linux
jobs:          
        include:
                - stage: test
                  script:  
                        - cd testing && python run_random.py ../vampire
  
