language: cpp
compiler: gcc
os:
        - linux
before_install:
        - sudo apt-get update
        - sudo apt-get install valgrind
jobs:
        include:
                - stage: test
                  script:  
                        - valgrind  --leak-check=full --show-leak-kinds=all ./vampire
