language: python
python:
        -"3.8"
os:
        - linux
jobs:          
        include:
                - stage: test
                  script:  
                        - cd testing && python run_random.py ../vampire
  
