language: cpp
compiler: gcc
os:
        - linux
before_install:
        - sudo apt-get update
        - sudo apt-get install valgrind
jobs:
        include:
                - stage: test
                  script: 
                        - sh run_tests.sh 
                        - valgrind --error-exitcode=1 --leak-check=full --show-leak-kinds=all .
