language: cpp
compiler: gcc
os:
        - linux
before_install:
        - sudo apt-get update
        - sudo apt-get install cppcheck
jobs:
        include:
                - stage: test
                  script:  
                        - cppcheck --enable=all --inconclusive -v .
  
